### Project2
:-<br>
Laptop data

In [1]:
# pip install pandas

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('laptopPrice.csv') #ye csv file ko read kar raha h

In [4]:
df # ye df variable bale file ko show kara raha h ek data frame ki tarh

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [5]:
df.drop('rating',axis=1) # ye rating ko drop kar raha h but temperory tarike se

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,18,4

In [6]:
df # uper  me rating ka column drop kiya tha but isme show ho raha h

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [7]:
df.drop(['rating','Number of Ratings','Number of Reviews'],axis=1,inplace=True)# ye jo drop me three columns permently delelte ho gye kiyu inplace=True ko use karoge to permanetly delete ho jayega

In [8]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490

In [9]:
df.isnull().sum() #ye null value ko dikha raha h

brand              0
processor_brand    0
processor_name     0
processor_gnrtn    0
ram_gb             0
ram_type           0
ssd                0
hdd                0
os                 0
os_bit             0
graphic_card_gb    0
weight             0
warranty           0
Touchscreen        0
msoffice           0
Price              0
dtype: int64

In [10]:
df.duplicated().sum()# ye total kitni duplicate value h ye dikha raha h

np.int64(37)

In [11]:
df.drop_duplicates(inplace=True)# permently drop ho gyi duplicte value

In [12]:
df.duplicated().sum()# ye total kitni duplicate value h ye dikha raha h

np.int64(0)

In [13]:
df[['brand']]

      brand
0      ASUS
1    Lenovo
2    Lenovo
3      ASUS
4      ASUS
..      ...
818    ASUS
819    ASUS
820    ASUS
821    ASUS
822  Lenovo

[786 rows x 1 columns]

In [14]:
df['brand'].unique()#brand ke columns ki unique value find kar li

<StringArray>
['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE']
Length: 8, dtype: str

In [15]:
df['brand'].value_counts()

brand
ASUS      234
DELL      147
Lenovo    143
HP        134
acer       51
MSI        49
APPLE      22
Avita       6
Name: count, dtype: int64

In [16]:
brand_dict={
    'ASUS':10, 'Lenovo':20, 'acer':30, 'Avita':40, 'HP':50, 'DELL':60, 'MSI':70, 'APPLE':80
}

In [17]:
df['brand']=df['brand'].map(brand_dict)#brand columns ki encoding kar di

In [18]:
df # ab show kar liya

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price
0,10,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649
1,20,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999
2,20,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999
3,10,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990
4,10,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,10,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990
819,10,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990
820,10,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990
821,10,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990
822,20,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490

In [19]:
df[['processor_brand']]

    processor_brand
0             Intel
1             Intel
2             Intel
3             Intel
4             Intel
..              ...
818             AMD
819             AMD
820             AMD
821             AMD
822             AMD

[786 rows x 1 columns]

In [20]:
df['processor_brand'].unique()

<StringArray>
['Intel', 'AMD', 'M1']
Length: 3, dtype: str

In [21]:
df['processor_brand'].value_counts()

processor_brand
Intel    582
AMD      185
M1        19
Name: count, dtype: int64

In [22]:
processor_brand_dict={
    'Intel':1, 'AMD':2, 'M1':3
}

In [23]:
df['processor_brand']=df['processor_brand'].map(processor_brand_dict)

In [24]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price
0,10,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649
1,20,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999
2,20,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999
3,10,1,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990
4,10,1,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,10,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990
819,10,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990
820,10,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990
821,10,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990
822,20,2,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490

In [25]:
df[['processor_name']]

    processor_name
0          Core i3
1          Core i3
2          Core i3
3          Core i5
4     Celeron Dual
..             ...
818        Ryzen 9
819        Ryzen 9
820        Ryzen 9
821        Ryzen 9
822        Ryzen 5

[786 rows x 1 columns]

In [26]:
df['processor_name'].unique()

<StringArray>
[     'Core i3',      'Core i5', 'Celeron Dual',      'Ryzen 5',
      'Core i7',      'Core i9',           'M1', 'Pentium Quad',
      'Ryzen 3',      'Ryzen 7',      'Ryzen 9']
Length: 11, dtype: str

In [27]:
df['processor_name'].value_counts()

processor_name
Core i5         277
Core i3         157
Core i7         104
Ryzen 5          80
Ryzen 7          55
Ryzen 3          26
Ryzen 9          25
Celeron Dual     23
M1               19
Pentium Quad     12
Core i9           8
Name: count, dtype: int64

In [28]:
processor_name_dict={
    'Core i3':3,      'Core i5':5, 'Celeron Dual':1,      'Ryzen 5':6,
      'Core i7':7,      'Core i9':9,           'M1':4, 'Pentium Quad':2,
      'Ryzen 3':11,      'Ryzen 7':8,      'Ryzen 9':10
}

In [29]:
df['processor_name']=df['processor_name'].map(processor_name_dict)

In [30]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price
0,10,1,3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649
1,20,1,3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999
2,20,1,3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999
3,10,1,5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990
4,10,1,1,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,10,2,10,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990
819,10,2,10,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990
820,10,2,10,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990
821,10,2,10,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990
822,20,2,6,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490

In [31]:
df[['processor_gnrtn']]

    processor_gnrtn
0              10th
1              10th
2              10th
3              10th
4     Not Available
..              ...
818   Not Available
819   Not Available
820   Not Available
821   Not Available
822            10th

[786 rows x 1 columns]

In [32]:
df['processor_gnrtn'].unique()

<StringArray>
['10th', 'Not Available', '11th', '7th', '8th', '9th', '4th', '12th']
Length: 8, dtype: str

In [33]:
df['processor_gnrtn'].value_counts()

processor_gnrtn
11th             319
Not Available    219
10th             196
8th               35
7th                7
9th                6
12th               3
4th                1
Name: count, dtype: int64

In [34]:
processor_gnrtn_dict={
    '10th':10, 'Not Available':0, '11th':11, '7th':7, '8th':8, '9th':9, '4th':4, '12th':12
}

In [35]:
df['processor_gnrtn']=df['processor_gnrtn'].map(processor_gnrtn_dict)

In [36]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price
0,10,1,3,10,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649
1,20,1,3,10,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999
2,20,1,3,10,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999
3,10,1,5,10,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990
4,10,1,1,0,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,10,2,10,0,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990
819,10,2,10,0,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990
820,10,2,10,0,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990
821,10,2,10,0,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990
822,20,2,6,10,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490

In [37]:
df[['ram_gb']]

    ram_gb
0     4 GB
1     4 GB
2     4 GB
3     8 GB
4     4 GB
..     ...
818   4 GB
819   4 GB
820   4 GB
821   4 GB
822   8 GB

[786 rows x 1 columns]

In [38]:
df['ram_gb'].unique()

<StringArray>
['4 GB', '8 GB', '16 GB', '32 GB']
Length: 4, dtype: str

In [39]:
df['ram_gb'].value_counts()

ram_gb
8 GB     393
4 GB     220
16 GB    171
32 GB      2
Name: count, dtype: int64

In [40]:
ram_gb_dict={
    '4 GB':4, '8 GB':8, '16 GB':16, '32 GB':32
}

In [41]:
df['ram_gb']=df['ram_gb'].map(ram_gb_dict)

In [42]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price
0,10,1,3,10,4,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649
1,20,1,3,10,4,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999
2,20,1,3,10,4,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999
3,10,1,5,10,8,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990
4,10,1,1,0,4,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,10,2,10,0,4,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990
819,10,2,10,0,4,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990
820,10,2,10,0,4,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990
821,10,2,10,0,4,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990
822,20,2,6,10,8,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490

In [43]:
df[['ram_type']]

    ram_type
0       DDR4
1       DDR4
2       DDR4
3       DDR4
4       DDR4
..       ...
818     DDR4
819     DDR4
820     DDR4
821     DDR4
822     DDR4

[786 rows x 1 columns]

In [44]:
df['ram_type'].unique()

<StringArray>
['DDR4', 'LPDDR4', 'LPDDR4X', 'DDR5', 'DDR3', 'LPDDR3']
Length: 6, dtype: str

In [45]:
df['ram_type'].value_counts()

ram_type
DDR4       678
LPDDR4X     52
LPDDR4      27
LPDDR3      14
DDR5         8
DDR3         7
Name: count, dtype: int64

In [46]:
ram_type_dict={
    'DDR4':1, 'LPDDR4':2, 'LPDDR4X':3, 'DDR5':4, 'DDR3':5, 'LPDDR3':6
    }

In [47]:
df['ram_type']=df['ram_type'].map(ram_type_dict)

In [48]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price
0,10,1,3,10,4,1,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649
1,20,1,3,10,4,1,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999
2,20,1,3,10,4,1,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999
3,10,1,5,10,8,1,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990
4,10,1,1,0,4,1,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,10,2,10,0,4,1,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990
819,10,2,10,0,4,1,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990
820,10,2,10,0,4,1,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990
821,10,2,10,0,4,1,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990
822,20,2,6,10,8,1,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490

In [49]:
df[['ssd']]

         ssd
0       0 GB
1       0 GB
2       0 GB
3     512 GB
4       0 GB
..       ...
818  1024 GB
819  1024 GB
820  1024 GB
821  1024 GB
822   512 GB

[786 rows x 1 columns]

In [50]:
df['ssd'].unique()

<StringArray>
['0 GB', '512 GB', '256 GB', '128 GB', '1024 GB', '2048 GB', '3072 GB']
Length: 7, dtype: str

In [51]:
df['ssd'].value_counts()

ssd
512 GB     379
256 GB     171
0 GB       122
1024 GB    108
128 GB       3
2048 GB      2
3072 GB      1
Name: count, dtype: int64

In [52]:
ssd_dict={
    '0 GB':0, '512 GB':512, '256 GB':256, '128 GB':128, '1024 GB':1024, '2048 GB':2048, '3072 GB':3072
}

In [53]:
df['ssd']=df['ssd'].map(ssd_dict)

In [54]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price
0,10,1,3,10,4,1,0,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649
1,20,1,3,10,4,1,0,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999
2,20,1,3,10,4,1,0,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999
3,10,1,5,10,8,1,512,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990
4,10,1,1,0,4,1,0,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,10,2,10,0,4,1,1024,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990
819,10,2,10,0,4,1,1024,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990
820,10,2,10,0,4,1,1024,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990
821,10,2,10,0,4,1,1024,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990
822,20,2,6,10,8,1,512,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490

In [55]:
df[['hdd']]

         hdd
0    1024 GB
1    1024 GB
2    1024 GB
3       0 GB
4     512 GB
..       ...
818     0 GB
819     0 GB
820     0 GB
821     0 GB
822     0 GB

[786 rows x 1 columns]

In [56]:
df['hdd'].unique()

<StringArray>
['1024 GB', '0 GB', '512 GB', '2048 GB']
Length: 4, dtype: str

In [57]:
df['hdd'].value_counts()

hdd
0 GB       588
1024 GB    157
512 GB      40
2048 GB      1
Name: count, dtype: int64

In [58]:
hdd_dict={
    '1024 GB':1024, '0 GB':0, '512 GB':512, '2048 GB':2048
}

In [59]:
df['hdd']=df['hdd'].map(hdd_dict)

In [60]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price
0,10,1,3,10,4,1,0,1024,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649
1,20,1,3,10,4,1,0,1024,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999
2,20,1,3,10,4,1,0,1024,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999
3,10,1,5,10,8,1,512,0,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990
4,10,1,1,0,4,1,0,512,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,10,2,10,0,4,1,1024,0,Windows,64-bit,0 GB,Casual,1 year,No,No,135990
819,10,2,10,0,4,1,1024,0,Windows,64-bit,0 GB,Casual,1 year,No,No,144990
820,10,2,10,0,4,1,1024,0,Windows,64-bit,4 GB,Casual,1 year,No,No,149990
821,10,2,10,0,4,1,1024,0,Windows,64-bit,4 GB,Casual,1 year,No,No,142990
822,20,2,6,10,8,1,512,0,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490

In [61]:
df[['os']]

          os
0    Windows
1    Windows
2    Windows
3    Windows
4    Windows
..       ...
818  Windows
819  Windows
820  Windows
821  Windows
822      DOS

[786 rows x 1 columns]

In [62]:
df['os'].unique()

<StringArray>
['Windows', 'DOS', 'Mac']
Length: 3, dtype: str

In [63]:
df['os'].value_counts()

os
Windows    748
Mac         22
DOS         16
Name: count, dtype: int64

In [64]:
os_dict={
    'Windows':1, 'DOS':2, 'Mac':3
    }

In [65]:
df['os']=df['os'].map(os_dict)

In [66]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price
0,10,1,3,10,4,1,0,1024,1,64-bit,0 GB,Casual,No warranty,No,No,34649
1,20,1,3,10,4,1,0,1024,1,64-bit,0 GB,Casual,No warranty,No,No,38999
2,20,1,3,10,4,1,0,1024,1,64-bit,0 GB,Casual,No warranty,No,No,39999
3,10,1,5,10,8,1,512,0,1,32-bit,2 GB,Casual,No warranty,No,No,69990
4,10,1,1,0,4,1,0,512,1,64-bit,0 GB,Casual,No warranty,No,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,10,2,10,0,4,1,1024,0,1,64-bit,0 GB,Casual,1 year,No,No,135990
819,10,2,10,0,4,1,1024,0,1,64-bit,0 GB,Casual,1 year,No,No,144990
820,10,2,10,0,4,1,1024,0,1,64-bit,4 GB,Casual,1 year,No,No,149990
821,10,2,10,0,4,1,1024,0,1,64-bit,4 GB,Casual,1 year,No,No,142990
822,20,2,6,10,8,1,512,0,2,64-bit,0 GB,ThinNlight,No warranty,No,No,57490

In [67]:
df[['os_bit']]

     os_bit
0    64-bit
1    64-bit
2    64-bit
3    32-bit
4    64-bit
..      ...
818  64-bit
819  64-bit
820  64-bit
821  64-bit
822  64-bit

[786 rows x 1 columns]

In [68]:
df['os_bit'].unique()

<StringArray>
['64-bit', '32-bit']
Length: 2, dtype: str

In [69]:
df['os_bit'].value_counts()

os_bit
64-bit    678
32-bit    108
Name: count, dtype: int64

In [70]:
os_bit_dict={
    '64-bit':64, '32-bit':32
}

In [71]:
df['os_bit']=df['os_bit'].map(os_bit_dict)

In [72]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price
0,10,1,3,10,4,1,0,1024,1,64,0 GB,Casual,No warranty,No,No,34649
1,20,1,3,10,4,1,0,1024,1,64,0 GB,Casual,No warranty,No,No,38999
2,20,1,3,10,4,1,0,1024,1,64,0 GB,Casual,No warranty,No,No,39999
3,10,1,5,10,8,1,512,0,1,32,2 GB,Casual,No warranty,No,No,69990
4,10,1,1,0,4,1,0,512,1,64,0 GB,Casual,No warranty,No,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,10,2,10,0,4,1,1024,0,1,64,0 GB,Casual,1 year,No,No,135990
819,10,2,10,0,4,1,1024,0,1,64,0 GB,Casual,1 year,No,No,144990
820,10,2,10,0,4,1,1024,0,1,64,4 GB,Casual,1 year,No,No,149990
821,10,2,10,0,4,1,1024,0,1,64,4 GB,Casual,1 year,No,No,142990
822,20,2,6,10,8,1,512,0,2,64,0 GB,ThinNlight,No warranty,No,No,57490

In [73]:
df[['graphic_card_gb']]

    graphic_card_gb
0              0 GB
1              0 GB
2              0 GB
3              2 GB
4              0 GB
..              ...
818            0 GB
819            0 GB
820            4 GB
821            4 GB
822            0 GB

[786 rows x 1 columns]

In [74]:
df['graphic_card_gb'].unique()

<StringArray>
['0 GB', '2 GB', '4 GB', '6 GB', '8 GB']
Length: 5, dtype: str

In [75]:
df['graphic_card_gb'].value_counts()

graphic_card_gb
0 GB    544
4 GB    125
2 GB     66
6 GB     37
8 GB     14
Name: count, dtype: int64

In [76]:
graphic_card_gb_dict={
    '0 GB':0, '2 GB':2, '4 GB':4, '6 GB':6, '8 GB':8
}

In [77]:
df['graphic_card_gb']=df['graphic_card_gb'].map(graphic_card_gb_dict)

In [78]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price
0,10,1,3,10,4,1,0,1024,1,64,0,Casual,No warranty,No,No,34649
1,20,1,3,10,4,1,0,1024,1,64,0,Casual,No warranty,No,No,38999
2,20,1,3,10,4,1,0,1024,1,64,0,Casual,No warranty,No,No,39999
3,10,1,5,10,8,1,512,0,1,32,2,Casual,No warranty,No,No,69990
4,10,1,1,0,4,1,0,512,1,64,0,Casual,No warranty,No,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,10,2,10,0,4,1,1024,0,1,64,0,Casual,1 year,No,No,135990
819,10,2,10,0,4,1,1024,0,1,64,0,Casual,1 year,No,No,144990
820,10,2,10,0,4,1,1024,0,1,64,4,Casual,1 year,No,No,149990
821,10,2,10,0,4,1,1024,0,1,64,4,Casual,1 year,No,No,142990
822,20,2,6,10,8,1,512,0,2,64,0,ThinNlight,No warranty,No,No,57490

In [79]:
df[['weight']]

         weight
0        Casual
1        Casual
2        Casual
3        Casual
4        Casual
..          ...
818      Casual
819      Casual
820      Casual
821      Casual
822  ThinNlight

[786 rows x 1 columns]

In [80]:
df['weight'].unique()

<StringArray>
['Casual', 'ThinNlight', 'Gaming']
Length: 3, dtype: str

In [81]:
df['weight'].value_counts()

weight
Casual        495
ThinNlight    252
Gaming         39
Name: count, dtype: int64

In [82]:
weight_dict={
    'Casual':1, 'ThinNlight':2, 'Gaming':3
}

In [83]:
df['weight']=df['weight'].map(weight_dict)

In [84]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price
0,10,1,3,10,4,1,0,1024,1,64,0,1,No warranty,No,No,34649
1,20,1,3,10,4,1,0,1024,1,64,0,1,No warranty,No,No,38999
2,20,1,3,10,4,1,0,1024,1,64,0,1,No warranty,No,No,39999
3,10,1,5,10,8,1,512,0,1,32,2,1,No warranty,No,No,69990
4,10,1,1,0,4,1,0,512,1,64,0,1,No warranty,No,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,10,2,10,0,4,1,1024,0,1,64,0,1,1 year,No,No,135990
819,10,2,10,0,4,1,1024,0,1,64,0,1,1 year,No,No,144990
820,10,2,10,0,4,1,1024,0,1,64,4,1,1 year,No,No,149990
821,10,2,10,0,4,1,1024,0,1,64,4,1,1 year,No,No,142990
822,20,2,6,10,8,1,512,0,2,64,0,2,No warranty,No,No,57490

In [85]:
df[['warranty']]

        warranty
0    No warranty
1    No warranty
2    No warranty
3    No warranty
4    No warranty
..           ...
818       1 year
819       1 year
820       1 year
821       1 year
822  No warranty

[786 rows x 1 columns]

In [86]:
df['warranty'].unique()

<StringArray>
['No warranty', '1 year', '2 years', '3 years']
Length: 4, dtype: str

In [87]:
df['warranty'].value_counts()

warranty
1 year         484
No warranty    266
2 years         23
3 years         13
Name: count, dtype: int64

In [88]:
warranty_dict={
    'No warranty':0, '1 year':1, '2 years':2, '3 years':3
}

In [89]:
df['warranty']=df['warranty'].map(warranty_dict)

In [90]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price
0,10,1,3,10,4,1,0,1024,1,64,0,1,0,No,No,34649
1,20,1,3,10,4,1,0,1024,1,64,0,1,0,No,No,38999
2,20,1,3,10,4,1,0,1024,1,64,0,1,0,No,No,39999
3,10,1,5,10,8,1,512,0,1,32,2,1,0,No,No,69990
4,10,1,1,0,4,1,0,512,1,64,0,1,0,No,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,10,2,10,0,4,1,1024,0,1,64,0,1,1,No,No,135990
819,10,2,10,0,4,1,1024,0,1,64,0,1,1,No,No,144990
820,10,2,10,0,4,1,1024,0,1,64,4,1,1,No,No,149990
821,10,2,10,0,4,1,1024,0,1,64,4,1,1,No,No,142990
822,20,2,6,10,8,1,512,0,2,64,0,2,0,No,No,57490

In [91]:
df[['Touchscreen']]

    Touchscreen
0            No
1            No
2            No
3            No
4            No
..          ...
818          No
819          No
820          No
821          No
822          No

[786 rows x 1 columns]

In [92]:
df['Touchscreen'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [93]:
df['Touchscreen'].value_counts()

Touchscreen
No     694
Yes     92
Name: count, dtype: int64

In [94]:
Touchscreen_dict={
    'No':0, 'Yes':1
}

In [95]:
df['Touchscreen']=df['Touchscreen'].map(Touchscreen_dict)

In [96]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price
0,10,1,3,10,4,1,0,1024,1,64,0,1,0,0,No,34649
1,20,1,3,10,4,1,0,1024,1,64,0,1,0,0,No,38999
2,20,1,3,10,4,1,0,1024,1,64,0,1,0,0,No,39999
3,10,1,5,10,8,1,512,0,1,32,2,1,0,0,No,69990
4,10,1,1,0,4,1,0,512,1,64,0,1,0,0,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,10,2,10,0,4,1,1024,0,1,64,0,1,1,0,No,135990
819,10,2,10,0,4,1,1024,0,1,64,0,1,1,0,No,144990
820,10,2,10,0,4,1,1024,0,1,64,4,1,1,0,No,149990
821,10,2,10,0,4,1,1024,0,1,64,4,1,1,0,No,142990
822,20,2,6,10,8,1,512,0,2,64,0,2,0,0,No,57490

In [97]:
df[['msoffice']]

    msoffice
0         No
1         No
2         No
3         No
4         No
..       ...
818       No
819       No
820       No
821       No
822       No

[786 rows x 1 columns]

In [98]:
df['msoffice'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [99]:
df['msoffice'].value_counts()

msoffice
No     512
Yes    274
Name: count, dtype: int64

In [100]:
msoffice_dict={
    'No':0, 'Yes':1
}

In [101]:
df['msoffice']=df['msoffice'].map(msoffice_dict)

In [102]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price
0,10,1,3,10,4,1,0,1024,1,64,0,1,0,0,0,34649
1,20,1,3,10,4,1,0,1024,1,64,0,1,0,0,0,38999
2,20,1,3,10,4,1,0,1024,1,64,0,1,0,0,0,39999
3,10,1,5,10,8,1,512,0,1,32,2,1,0,0,0,69990
4,10,1,1,0,4,1,0,512,1,64,0,1,0,0,0,26990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,10,2,10,0,4,1,1024,0,1,64,0,1,1,0,0,135990
819,10,2,10,0,4,1,1024,0,1,64,0,1,1,0,0,144990
820,10,2,10,0,4,1,1024,0,1,64,4,1,1,0,0,149990
821,10,2,10,0,4,1,1024,0,1,64,4,1,1,0,0,142990
822,20,2,6,10,8,1,512,0,2,64,0,2,0,0,0,57490

In [103]:
# df.to_csv('clean_laptopPrice.csv')

In [104]:
x=df.drop('Price',axis=1)

In [105]:
x

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice
0,10,1,3,10,4,1,0,1024,1,64,0,1,0,0,0
1,20,1,3,10,4,1,0,1024,1,64,0,1,0,0,0
2,20,1,3,10,4,1,0,1024,1,64,0,1,0,0,0
3,10,1,5,10,8,1,512,0,1,32,2,1,0,0,0
4,10,1,1,0,4,1,0,512,1,64,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,10,2,10,0,4,1,1024,0,1,64,0,1,1,0,0
819,10,2,10,0,4,1,1024,0,1,64,0,1,1,0,0
820,10,2,10,0,4,1,1024,0,1,64,4,1,1,0,0
821,10,2,10,0,4,1,1024,0,1,64,4,1,1,0,0
822,20,2,6,10,8,1,512,0,2,64,0,2,0,0,0

In [106]:
y=df[['Price']]

In [107]:
y

      Price
0     34649
1     38999
2     39999
3     69990
4     26990
..      ...
818  135990
819  144990
820  149990
821  142990
822   57490

[786 rows x 1 columns]

In [108]:
# pip install scikit-learn

In [109]:
# pip install matplotlib

In [110]:
# pip install seaborn

In [111]:
# pip install numpy

In [112]:
import sklearn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC,SVR
import joblib

In [113]:
from sklearn.model_selection import train_test_split
x_train , x_test ,y_train ,y_test =train_test_split(x,y,test_size=0.2,random_state=42)

In [114]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(628, 15) (158, 15) (628, 1) (158, 1)

In [115]:
x_train

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice
218,50,1,5,11,16,1,512,0,1,64,0,2,1,0,1
140,10,1,3,11,8,1,0,1024,1,64,0,1,1,0,0
778,10,2,8,0,16,3,1024,0,1,64,0,1,0,1,0
546,10,1,7,10,16,1,1024,0,1,64,6,1,1,1,0
57,50,1,3,11,4,1,256,0,1,64,0,2,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,20,1,3,10,4,1,256,0,1,32,0,1,0,0,0
112,10,1,3,11,8,1,512,0,1,64,0,2,1,0,1
281,20,1,5,11,8,1,512,0,1,64,0,2,1,0,1
456,10,1,5,11,16,1,256,1024,1,64,0,1,1,0,1
108,60,1,3,11,8,1,512,0,1,64,0,1,1,1,0

In [116]:
y_train

      Price
218   67990
140   38900
778  112990
546  224990
57    44900
..      ...
73    41990
112   44990
281   54990
456   64990
108   60790

[628 rows x 1 columns]

In [117]:
x_test

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice
789,10,2,8,0,4,3,1024,0,1,64,4,1,1,1,0
40,60,1,3,10,4,1,256,0,1,64,0,2,1,0,1
219,10,1,5,10,8,1,512,0,1,64,4,3,1,0,0
207,30,1,5,7,8,5,256,0,1,64,0,2,1,0,1
243,50,1,5,11,8,1,512,0,1,64,0,2,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,60,1,3,11,8,1,256,0,1,64,0,1,1,0,0
155,60,1,3,10,4,1,0,1024,1,64,0,2,1,0,1
347,60,1,5,11,8,1,512,0,1,64,2,2,3,0,0
519,50,1,7,11,16,1,512,0,1,64,0,1,1,1,1
464,20,1,5,10,8,1,256,1024,1,64,4,3,0,0,0

In [118]:
y_test

     Price
789  99990
40   36990
219  57990
207  86867
243  58340
..     ...
82   48500
155  43000
347  71990
519  99999
464  74590

[158 rows x 1 columns]

In [119]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [120]:
lr.fit(x_train, y_train)

LinearRegression()

In [121]:
joblib.dump(lr,"linear_model.lb")

['linear_model.lb']

In [122]:
model=joblib.load('linear_model.lb')

In [123]:
model.predict(x_test)

array([[144361.99722067],
       [ 27194.91334494],
       [ 74054.98792735],
       [ 68606.81444972],
       [ 57707.52159241],
       [ 72482.73013746],
       [157360.36830263],
       [ 26869.47015683],
       [200257.32447714],
       [ 25997.01133511],
       [ 73142.17108016],
       [ 58336.94213444],
       [ 43695.17060685],
       [149141.71705482],
       [ 43695.17060685],
       [ 27734.32712803],
       [158722.8104221 ],
       [ 49298.44222149],
       [152963.95287617],
       [ 96206.01427371],
       [119158.80152054],
       [ 75901.2092446 ],
       [ 72700.20338323],
       [ 77445.32337058],
       [ 28100.74277822],
       [ 56209.49500549],
       [ 30009.68338205],
       [ 91294.92734603],
       [ 71406.97109385],
       [ 73876.66826044],
       [ 71906.31328949],
       [ 96206.01427371],
       [ 74509.68092617],
       [ 47886.31979781],
       [ 48249.78045236],
       [ 66386.89180249],
       [135642.84295455],
       [138580.7284153 ],
       [ 93741.48770053],
       [150194.26464485],
       [ 64462.08825161],
       [ 77857.64664084],
       [142050.66153122],
       [ 43520.04418685],
       [ 53295.45398321],
       [ 52719.90283071],
       [ 66857.70473071],
       [ 54244.16099663],
       [ 49298.44222149],
       [ 26271.2497329 ],
       [ 54063.99396636],
       [ 96206.01427371],
       [ 51425.88935044],
       [ 31550.3055719 ],
       [ 28600.08497385],
       [ 74520.17050747],
       [ 81070.33173173],
       [ 40597.03250746],
       [ 81658.7764116 ],
       [ 56209.49500549],
       [127261.4149804 ],
       [ 64366.14479155],
       [ 33677.75270085],
       [ 34859.58781564],
       [ 33178.41050521],
       [ 32679.06830957],
       [154866.29868457],
       [ 39671.99450551],
       [ 83896.33867487],
       [ 87117.53698291],
       [138286.91127704],
       [ 70412.29461272],
       [ 74054.98792735],
       [ 54233.67141533],
       [ 94599.41172204],
       [ 94664.83549727],
       [ 70523.15874575],
       [ 54707.49621339],
       [ 96694.83654006],
       [ 76383.82316831],
       [ 59848.27593328],
       [ 47559.25084693],
       [ 86236.12434936],
       [127521.25802012],
       [ 67919.68623023],
       [ 43839.33065824],
       [159852.45327429],
       [ 51155.54296434],
       [ 87616.87917855],
       [176448.29568341],
       [ 80316.56022818],
       [ 60076.42842081],
       [145536.13936343],
       [ 50247.14923492],
       [ 62717.19689416],
       [ 32684.87150427],
       [103972.08588452],
       [ 67536.8007783 ],
       [150248.9346001 ],
       [ 49797.78441713],
       [ 83613.26761401],
       [ 57564.73281821],
       [ 75829.42340551],
       [ 73087.113513  ],
       [ 29563.82017335],
       [104433.98791615],
       [ 75740.32092127],
       [ 58121.00020236],
       [ 32040.27474116],
       [104183.0942631 ],
       [ 64700.58652796],
       [ 70244.41887548],
       [ 93237.23856143],
       [ 49428.52056789],
       [135478.80000946],
       [ 57707.52159241],
       [ 28823.01827826],
       [139206.47854558],
       [116839.40816888],
       [117233.96250171],
       [ 40597.03250746],
       [ 95545.62771995],
       [ 61541.55453855],
       [ 29923.77921882],
       [ 41303.29775982],
       [ 55113.8544158 ],
       [ 79219.75884873],
       [ 47886.31979781],
       [103008.42390536],
       [ 87696.35354543],
       [ 82661.45387829],
       [ 71254.91743192],
       [ 60076.42842081],
       [ 60334.310917  ],
       [ 64390.75287575],
       [ 69946.90028778],
       [ 53704.74721354],
       [ 53255.38239576],
       [ 73606.0328165 ],
       [ 72645.14581607],
       [ 32377.91590494],
       [119014.66634678],
       [ 53911.94030443],
       [ 93470.64898437],
       [ 59335.62652572],
       [ 55429.93010343],
       [ 75875.29818766],
       [114032.16737577],
       [ 48858.0598153 ],
       [ 57503.43044464],
       [ 57693.43988741],
       [157879.60652275],
       [ 68509.19805699],
       [ 39542.05489873],
       [ 26551.41109791],
       [ 66689.95674472],
       [102499.93176263],
       [ 75740.32092127]])

In [124]:
x_test

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice
789,10,2,8,0,4,3,1024,0,1,64,4,1,1,1,0
40,60,1,3,10,4,1,256,0,1,64,0,2,1,0,1
219,10,1,5,10,8,1,512,0,1,64,4,3,1,0,0
207,30,1,5,7,8,5,256,0,1,64,0,2,1,0,1
243,50,1,5,11,8,1,512,0,1,64,0,2,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,60,1,3,11,8,1,256,0,1,64,0,1,1,0,0
155,60,1,3,10,4,1,0,1024,1,64,0,2,1,0,1
347,60,1,5,11,8,1,512,0,1,64,2,2,3,0,0
519,50,1,7,11,16,1,512,0,1,64,0,1,1,1,1
464,20,1,5,10,8,1,256,1024,1,64,4,3,0,0,0

In [125]:
pred =lr.predict(x_test)

In [126]:
pred

array([[144361.99722067],
       [ 27194.91334494],
       [ 74054.98792735],
       [ 68606.81444972],
       [ 57707.52159241],
       [ 72482.73013746],
       [157360.36830263],
       [ 26869.47015683],
       [200257.32447714],
       [ 25997.01133511],
       [ 73142.17108016],
       [ 58336.94213444],
       [ 43695.17060685],
       [149141.71705482],
       [ 43695.17060685],
       [ 27734.32712803],
       [158722.8104221 ],
       [ 49298.44222149],
       [152963.95287617],
       [ 96206.01427371],
       [119158.80152054],
       [ 75901.2092446 ],
       [ 72700.20338323],
       [ 77445.32337058],
       [ 28100.74277822],
       [ 56209.49500549],
       [ 30009.68338205],
       [ 91294.92734603],
       [ 71406.97109385],
       [ 73876.66826044],
       [ 71906.31328949],
       [ 96206.01427371],
       [ 74509.68092617],
       [ 47886.31979781],
       [ 48249.78045236],
       [ 66386.89180249],
       [135642.84295455],
       [138580.7284153 ],
       [ 93741.48770053],
       [150194.26464485],
       [ 64462.08825161],
       [ 77857.64664084],
       [142050.66153122],
       [ 43520.04418685],
       [ 53295.45398321],
       [ 52719.90283071],
       [ 66857.70473071],
       [ 54244.16099663],
       [ 49298.44222149],
       [ 26271.2497329 ],
       [ 54063.99396636],
       [ 96206.01427371],
       [ 51425.88935044],
       [ 31550.3055719 ],
       [ 28600.08497385],
       [ 74520.17050747],
       [ 81070.33173173],
       [ 40597.03250746],
       [ 81658.7764116 ],
       [ 56209.49500549],
       [127261.4149804 ],
       [ 64366.14479155],
       [ 33677.75270085],
       [ 34859.58781564],
       [ 33178.41050521],
       [ 32679.06830957],
       [154866.29868457],
       [ 39671.99450551],
       [ 83896.33867487],
       [ 87117.53698291],
       [138286.91127704],
       [ 70412.29461272],
       [ 74054.98792735],
       [ 54233.67141533],
       [ 94599.41172204],
       [ 94664.83549727],
       [ 70523.15874575],
       [ 54707.49621339],
       [ 96694.83654006],
       [ 76383.82316831],
       [ 59848.27593328],
       [ 47559.25084693],
       [ 86236.12434936],
       [127521.25802012],
       [ 67919.68623023],
       [ 43839.33065824],
       [159852.45327429],
       [ 51155.54296434],
       [ 87616.87917855],
       [176448.29568341],
       [ 80316.56022818],
       [ 60076.42842081],
       [145536.13936343],
       [ 50247.14923492],
       [ 62717.19689416],
       [ 32684.87150427],
       [103972.08588452],
       [ 67536.8007783 ],
       [150248.9346001 ],
       [ 49797.78441713],
       [ 83613.26761401],
       [ 57564.73281821],
       [ 75829.42340551],
       [ 73087.113513  ],
       [ 29563.82017335],
       [104433.98791615],
       [ 75740.32092127],
       [ 58121.00020236],
       [ 32040.27474116],
       [104183.0942631 ],
       [ 64700.58652796],
       [ 70244.41887548],
       [ 93237.23856143],
       [ 49428.52056789],
       [135478.80000946],
       [ 57707.52159241],
       [ 28823.01827826],
       [139206.47854558],
       [116839.40816888],
       [117233.96250171],
       [ 40597.03250746],
       [ 95545.62771995],
       [ 61541.55453855],
       [ 29923.77921882],
       [ 41303.29775982],
       [ 55113.8544158 ],
       [ 79219.75884873],
       [ 47886.31979781],
       [103008.42390536],
       [ 87696.35354543],
       [ 82661.45387829],
       [ 71254.91743192],
       [ 60076.42842081],
       [ 60334.310917  ],
       [ 64390.75287575],
       [ 69946.90028778],
       [ 53704.74721354],
       [ 53255.38239576],
       [ 73606.0328165 ],
       [ 72645.14581607],
       [ 32377.91590494],
       [119014.66634678],
       [ 53911.94030443],
       [ 93470.64898437],
       [ 59335.62652572],
       [ 55429.93010343],
       [ 75875.29818766],
       [114032.16737577],
       [ 48858.0598153 ],
       [ 57503.43044464],
       [ 57693.43988741],
       [157879.60652275],
       [ 68509.19805699],
       [ 39542.05489873],
       [ 26551.41109791],
       [ 66689.95674472],
       [102499.93176263],
       [ 75740.32092127]])

In [127]:
df['brand'].unique()

array([10, 20, 30, 40, 50, 60, 70, 80])

In [128]:
x

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice
0,10,1,3,10,4,1,0,1024,1,64,0,1,0,0,0
1,20,1,3,10,4,1,0,1024,1,64,0,1,0,0,0
2,20,1,3,10,4,1,0,1024,1,64,0,1,0,0,0
3,10,1,5,10,8,1,512,0,1,32,2,1,0,0,0
4,10,1,1,0,4,1,0,512,1,64,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,10,2,10,0,4,1,1024,0,1,64,0,1,1,0,0
819,10,2,10,0,4,1,1024,0,1,64,0,1,1,0,0
820,10,2,10,0,4,1,1024,0,1,64,4,1,1,0,0
821,10,2,10,0,4,1,1024,0,1,64,4,1,1,0,0
822,20,2,6,10,8,1,512,0,2,64,0,2,0,0,0

solve/using SVR

In [129]:
# sv=SVR()

In [130]:
# sv.fit(x_train, y_train)

In [131]:
# sv.score(x_train,y_train)

In [132]:
# sv.score(x_test,y_test)

In [133]:
# pred=sv.predict(x_test)

In [134]:
# pred

In [135]:
# y_test

In [136]:
# df['Price'].value_counts()

sv=SVR